// Generated by CoffeeScript 1.8.0
(function() {
  var DogCategory, dogs, dogsJson, fs, transliteration;

  fs = require('fs');

  transliteration = require('transliteration');

  DogCategory = require('./dog_model');

  dogs = fs.readFileSync('output.json', 'utf-8');

  dogsJson = JSON.parse(dogs);

}).call(this);

//# sourceMappingURL=app.js.map
