// Generated by CoffeeScript 1.8.0
(function() {
  var DogCategory, async, fs, transliteration;

  fs = require('fs');

  transliteration = require('transliteration');

  DogCategory = require('./dog_model');

  async = require('async');

  async.auto({
    getDogs: function(cb) {
      return DogCategory.find(function(err, row, sql) {
        if (err) {
          return console.log(err);
        }
        return cb(null, row);
      });
    },
    changeDogs: [
      'getDogs', function(cb, result) {
        var dogs, i, _i, _len;
        dogs = result.getDogs;
        for (_i = 0, _len = dogs.length; _i < _len; _i++) {
          i = dogs[_i];
          console.log(i);
          i.en_name = i.pinyin_name;
          i.pinyin_name = transliteration.slugify(i.name, {
            lowercase: false,
            separator: ''
          });
          i.first_letter = i.pinyin_name[0];
          i.save();
        }
        return console.log("ok");
      }
    ]
  });

}).call(this);

//# sourceMappingURL=app.js.map
