// Generated by CoffeeScript 1.8.0
(function() {
  var DogCategory, dogInfo, dogs, dogsJson, fs, i, newDog, transliteration, _i, _len;

  fs = require('fs');

  transliteration = require('transliteration');

  DogCategory = require('./dog_model');

  dogs = fs.readFileSync('output.json', 'utf-8');

  dogsJson = JSON.parse(dogs);

  for (_i = 0, _len = dogsJson.length; _i < _len; _i++) {
    i = dogsJson[_i];
    dogInfo = {
      name: i['犬种中文'],
      pinyin_name: i['犬种英文'],
      first_letter: i['犬种英文'][0],
      desc: i['犬组']
    };
    newDog = DogCategory.build(dogInfo);
    newDog.save(function(err, row, sql) {
      if (err) {
        return console.log(err);
      }
      return console.log(sql);
    });
  }

}).call(this);

//# sourceMappingURL=app.js.map
