// Generated by CoffeeScript 1.8.0
(function() {
  var T, options, toshihiko;

  T = require("toshihiko");

  if (process.env.NODE_ENV === "procuct") {
    options = {
      host: process.env.MYSQL_HOST
    };
    toshihiko = new T.Toshihiko(process.env.DATABASE, process.env.MYSQL_NAME, process.env.MYSQL_PASSWORD, options);
    console.log("use procuct databases");
  } else {
    toshihiko = new T.Toshihiko("ggbnb", "root", "", {});
    console.log("use localhost databases");
  }

  module.exports = toshihiko;

}).call(this);

//# sourceMappingURL=toshihiko.js.map
